// src/modules/common/errorCodes.js
const ERROR_CODES = {
  // 400
  BAD_REQUEST: "BAD_REQUEST",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  INVALID_QUERY_PARAM: "INVALID_QUERY_PARAM",

  // 401/403 (B에서 주로 사용)
  UNAUTHORIZED: "UNAUTHORIZED",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  FORBIDDEN: "FORBIDDEN",

  // 404
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",

  // 409/422
  DUPLICATE_RESOURCE: "DUPLICATE_RESOURCE",
  STATE_CONFLICT: "STATE_CONFLICT",
  UNPROCESSABLE_ENTITY: "UNPROCESSABLE_ENTITY",

  // 429
  TOO_MANY_REQUESTS: "TOO_MANY_REQUESTS",

  // 500/503
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
};

module.exports = { ERROR_CODES };
